### ISSUE TITLE
Telegram Notification

### ISSUE THREAD

**Issue by c0rrre** [liofal/streamlink#1]
Hi,

is it possible to add telegram notification instead of slack?
Would be very nice.

Thanks for the nice project.

**Comment by liofal** [comment]
that seems a reasonable request, although I would rather add it as an addition and not a replacement

**Comment by liofal** [comment]
hey, sorry it took me long enough, and probably it's no longer needed, well anyway, it's now available in version 3.0.0...

**Comment by c0rrre** [comment]
Thanks :)
