### ISSUE TITLE
Variable passthrough broken

### ISSUE THREAD

**Issue by too-many-bees** [liofal/streamlink#10]
Hey there,
I assume that something isn't working after you redid the Docker file. I had to update the container yesterday and there seems to be something wrong with the pass through of the variables.
![Screenshot 2024-01-03 202400](https://github.com/liofal/streamlink/assets/131194480/d65f0c3a-1602-4a52-a240-e2efeb77564e)

**Comment by liofal** [comment]
indeed, sorry about that, poor cache testing from my end, let me know if 2.0.2 solves it

**Comment by too-many-bees** [comment]
Seems to work now. Thanks for the quick fix.

**Comment by too-many-bees** [comment]
Ok, update. There's no output. The logs say it's writing a file, but it doesn't show up. I set the output folder to several different local and SMB directories to rule out permission issues on my side, but it wont write to any of them. Are you able to reproduce that?

**Comment by liofal** [comment]
so far I dont reproduce it, if I startup the container without mounting up any volume it writes down the file in a download folder within the container, are you using docker desktop? if yes, on macOS something similar happen to me when I ran vistiofs

**Comment by liofal** [comment]
![Screenshot 2024-01-06 at 12 20 59](https://github.com/liofal/streamlink/assets/717272/46657f8f-2a58-4e24-982a-37a968f0638a)
here is a sample of it running in a code spaces environment, be mindful if you use the docker compose container, that the userid must have privileges to write to the output

**Comment by liofal** [comment]
found it, should be fixed now, sorry about that...

**Comment by liofal** [comment]
is this fixed for you too?
