### ISSUE TITLE
RuntimeError at latest channel

### ISSUE THREAD

**Issue by BimmerZug** [liofal/streamlink#15]
The container starts normally. After two minutes it is stopped and the following is listed under Logs:

```
2024/04/07 14:29:21 | stdout | RuntimeError: can't create new thread at interpreter shutdown
2024/04/07 14:29:21 | stdout | _start_new_thread(self._bootstrap, ())
2024/04/07 14:29:21 | stdout | File "/usr/local/lib/python3.12/threading.py", line 992, in start
2024/04/07 14:29:21 | stdout | t.start()
2024/04/07 14:29:21 | stdout | File "/app/./streamlink-recorder.py", line 128, in loopcheck
2024/04/07 14:29:21 | stdout | self.function(*self.args, **self.kwargs)
2024/04/07 14:29:21 | stdout | File "/usr/local/lib/python3.12/threading.py", line 1431, in run
2024/04/07 14:29:21 | stdout | self.run()
2024/04/07 14:29:21 | stdout | File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
2024/04/07 14:29:21 | stdout | Traceback (most recent call last):
2024/04/07 14:29:21 | stdout | Exception in thread Thread-1:
```

**Comment by liofal** [comment]
hi there, can you tell me more about how do you startup the container?

share your compose or deployment script, is it docker as a CRI? running on linux?

**Comment by liofal** [comment]
ah yes, you are running on synology I remember now, so the "latest" tag is failing for you, let me see, and get back to you

**Comment by liofal** [comment]
will you try and see if this version fixes your issue?
image: ghcr.io/liofal/streamlink:pr-14

**Comment by BimmerZug** [comment]
> will you try and see if this version fixes your issue? image: ghcr.io/liofal/streamlink:pr-14

I'm sure I had already replied but somehow I didn't press send. Maybe. In any case, it works with this version. Thank you very much.

**Comment by liofal** [comment]
sure, thanks for the update, now keep in mind I have shared with you a preview release, which as not yet been merged to the master branch, if you want to remain up to date with th future release you will have to switch back to the master branch once pr is released.
