### ISSUE TITLE
Cant record any more

### ISSUE THREAD

**Issue by c0rrre** [liofal/streamlink#2]
Hi,

Do someone else has the problem that recording a twitch stream dont work anymore?

In the official streamlink repo there is an closed issue which is fixed in streamlink-2.0, but the docker container uses streamlink-1.7.

Is it possible to use the updated version?

Greetz c0rrre

**Comment by liofal** [comment]
can you clarify what's the issue?

I update to latest python and pushed 1.8.5, it record with no issue
did you update clientid.env? twitch moved into an oauth client authentication, you now need to specify clientid and clientsecret

**Comment by liofal** [comment]
![Screenshot 2021-01-30 at 06 22 31](https://user-images.githubusercontent.com/717272/106348067-96053300-62c3-11eb-8018-1f4c9bcae499.png)

here is my latest trace running the test service

**Comment by c0rrre** [comment]
Looks like it is working again, thanks
