### ISSUE TITLE
live check doesn't loop

### ISSUE THREAD

**Issue by too-many-bees** [liofal/streamlink#6]
Hi,
This is exactly what I was looking for, great work.
Unfortunately I'm having a weird issue: When I start the container and the streamer is already live, the download works perfectly. However if the stream isn't live, it goes through the streamlink-recorder.py once, returns "currently offline, checking again in 360 seconds" and then exits instead of retrying. I can not find an exit condition in the script that would explain that. Is there something obvious that I'm missing?

**Comment by liofal** [comment]
hi there, glad to hear that you have this repository useful.
that's indeed strange, and doesn't reflect the component design and behaviour from my end... 
can you clarify a bit, how do you initialise this?
what stream are you trying to capture?
here is a screen capture of my "serral" sc2 stream container running and waiting for a new stream to start. it's initialised when the streamer is offline.
![Screenshot 2023-04-23 at 10 27 02](https://user-images.githubusercontent.com/717272/233828761-46b9f4ec-2175-4565-bf25-88d42092e142.png)

**Comment by liofal** [comment]
hi there, thanks again for reporting it for some reason I was unable to reproduce it properly, I have now been facing the same issue, which is an indention issue during the last refactoring
it has now been solved in v2.0.1, please upgrade to this version and let me know.

**Comment by too-many-bees** [comment]
Hi, I just updated and it works now. Thanks for looking into it.
